network={
    key_mgmt=IEEE8021X
    eap=TLS
    identity="TPM2 Test Certificate"
    ca_cert="/opt/8021x-eap-tls-ibmtss/client/ca-lab.crt"
    client_cert="/opt/8021x-eap-tls-ibmtss/client/tpmtest.crt"
    private_key="/opt/8021x-eap-tls-ibmtss/client/tpmtest.key"
    private_key_passwd=""
}
